import Head from "next/head";
import NavBar from "../views/Main/nav-bar";
import { useRouter } from "next/router";
import FolderDetail from "../views/Folders/FolderItem/folder-detail";

export default function DetailFolder() {
  const router = useRouter();
  const { folderItemId } = router.query;

  return (
    <div className="container justify-center items-end mx-auto px-3">
      <Head>
        <title>Folder Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar />
        <FolderDetail
          folderId={Number(folderItemId)}
          id={0}
          label={""}
          detail={""}
          createDate={""}
          state={""}
          history={[]}
        />
      </main>
    </div>
  );
}
