import Head from 'next/head'
import FoldersBody from './views/Main/FoldersBody'
import NavBar from './views/Main/NavBar'


export default function Home() {
  return (
    <div className='container justify-center items-end mx-auto px-3'>
      <Head>
        <title>Folders List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar />
        <FoldersBody />
      </main>
    </div>
  )
}
